
#ifndef GUARD_CONSTANTS_BATTLE_PARTNERS_H
#define GUARD_CONSTANTS_BATTLE_PARTNERS_H

#define PARTNER_NONE 0
#define PARTNER_STEVEN 1
#define PARTNER_BRENDAN 2
#define PARTNER_MAY 3
#define PARTNER_COUNT 4

#endif  // GUARD_CONSTANTS_BATTLE_PARTNERS_H
