#ifndef GUARD_CONSTANTS_TMS_HMS_H
#define GUARD_CONSTANTS_TMS_HMS_H

#define FOREACH_TM(F) \
    F(FOCUS_PUNCH) \
    F(DRAGON_CLAW) \
    F(WATER_PULSE) \
    F(CALM_MIND) \
    F(ROAR) \
    F(VENOSHOCK) \
    F(HAIL) \
    F(BULK_UP) \
    F(BULLET_SEED) \
    F(TRAILBLAZE) \
    F(SUNNY_DAY) \
    F(TAUNT) \
    F(ICE_BEAM) \
    F(BLIZZARD) \
    F(HYPER_BEAM) \
    F(LIGHT_SCREEN) \
    F(PROTECT) \
    F(RAIN_DANCE) \
    F(GIGA_DRAIN) \
    F(SAFEGUARD) \
    F(FRUSTRATION) \
    F(SOLAR_BEAM) \
    F(IRON_TAIL) \
    F(THUNDERBOLT) \
    F(THUNDER) \
    F(EARTHQUAKE) \
    F(RETURN) \
    F(DIG) \
    F(PSYCHIC) \
    F(SHADOW_BALL) \
    F(BRICK_BREAK) \
    F(DOUBLE_TEAM) \
    F(REFLECT) \
    F(SHOCK_WAVE) \
    F(FLAMETHROWER) \
    F(SLUDGE_BOMB) \
    F(SANDSTORM) \
    F(FIRE_BLAST) \
    F(ROCK_TOMB) \
    F(AERIAL_ACE) \
    F(ROUND) \
    F(FACADE) \
    F(SECRET_POWER) \
    F(REST) \
    F(FLAME_CHARGE) \
    F(THIEF) \
    F(STEEL_WING) \
    F(SKILL_SWAP) \
    F(LOW_SWEEP) \
    F(OVERHEAT) \
    F(PSYSHOCK) \
    F(FOCUS_BLAST) \
    F(ENERGY_BALL) \
    F(FALSE_SWIPE) \
    F(STOMPING_TANTRUM) \
    F(FLING) \
    F(ELECTROWEB) \
    F(SPLASH) \
    F(TACKLE) \
    F(POUND) \
    F(WILL_O_WISP) \
    F(ACROBATICS) \
    F(INCINERATE) \
    F(EXPLOSION) \
    F(SHADOW_CLAW) \
    F(PAYBACK) \
    F(RETALIATE) \
    F(DOUBLE_EDGE) \
    F(ROCK_POLISH) \
    F(DRAIN_PUNCH) \
    F(STONE_EDGE) \
    F(VOLT_SWITCH) \
    F(THUNDER_WAVE) \
    F(GYRO_BALL) \
    F(SWORDS_DANCE) \
    F(STRUGGLE_BUG) \
    F(PSYCHIC_NOISE) \
    F(BULLDOZE) \
    F(TRIPLE_AXEL) \
    F(ROCK_SLIDE) \
    F(X_SCISSOR) \
    F(DRAGON_TAIL) \
    F(INFESTATION) \
    F(POISON_JAB) \
    F(HIGH_HORSEPOWER) \
    F(GRASS_KNOT) \
    F(SWAGGER) \
    F(SLEEP_TALK) \
    F(U_TURN) \
    F(AIR_CUTTER) \
    F(FLASH_CANNON) \
    F(TRICK_ROOM) \
    F(WILD_CHARGE) \
    F(THROAT_CHOP) \
    F(SNARL) \
    F(MUD_SPORT) \
    F(DARK_PULSE) \
    F(WATER_SPORT) \
    F(DAZZLING_GLEAM) \
    F(BODY_PRESS)

#define FOREACH_HM(F) \
    F(CUT) \
    F(FLY) \
    F(SURF) \
    F(STRENGTH) \
    F(FLASH) \
    F(ROCK_SMASH) \
    F(WATERFALL) \
    F(DIVE)

#define FOREACH_TMHM(F) \
    FOREACH_TM(F) \
    FOREACH_HM(F)

#endif
