#!/usr/bin/env python3
"""Generate the game-charmap -> ASCII table used when exporting the party as text.

In-game strings use the GBA charmap (see charmap.txt), not ASCII. Exporting a
party as Showdown/pokepaste syntax needs plain ASCII, so this emits a flat
lookup table indexed by charmap byte.

Only the Latin section of charmap.txt is read: the Hiragana and Katakana
sections below it reuse the same byte values (both 'A-grave' and 'a' are 0x01),
so parsing past that point would silently corrupt the Latin mappings.

Usage (from the repo root):
    python3 tools/gen_charmap_ascii.py > src/data/charmap_ascii.h
"""
import re
import sys
import unicodedata

CHARMAP = "charmap.txt"
STOP_AT = "@ Hiragana"

# Characters NFD decomposition cannot fold, plus deliberate choices.
#
# The gender symbols matter for species IDs: Showdown resolves species with
# toID(), which strips non-alphanumerics, so "Nidoran-F" and "NidoranF" both
# reduce to "nidoranf". Emitting "-F"/"-M" keeps the text readable too.
SPECIAL = {
    "ß": "ss",   # sharp s
    "Œ": "OE", "œ": "oe",
    "¿": "?",  "¡": "!",
    "º": "o",  "ª": "a",
    "…": "...",
    "“": '"',  "”": '"',
    "‘": "'",  "’": "'",
    "♂": "-M",             # male sign
    "♀": "-F",             # female sign
    "¥": "Y",
    "×": "x",
    "·": ".",
    "▶": ">",
}

# Named (non-quoted) charmap entries worth carrying across.
NAMED = {
    "PK": "PK",
    "SUPER_ER": "er",
    "SUPER_RE": "re",
    "SUPER_E": "e",
    "NBSP": " ",
    "UNK_SPACER": " ",
}

# 0xFF is the string terminator (charmap spells it '$'); never emit it as data.
EXCLUDE_BYTES = {0xFF}

LINE_RE = re.compile(r"^\s*(?:'(\\?.)'|([A-Z0-9_]+))\s*=\s*([0-9A-Fa-f]{2}(?:\s+[0-9A-Fa-f]{2})*)")


def fold(ch):
    """Best-effort single character -> ASCII."""
    if ch in SPECIAL:
        return SPECIAL[ch]
    if ord(ch) < 0x80:
        return ch
    decomposed = unicodedata.normalize("NFD", ch)
    stripped = "".join(c for c in decomposed if not unicodedata.combining(c))
    return stripped if all(ord(c) < 0x80 for c in stripped) else None


def parse():
    table = {}
    with open(CHARMAP, encoding="utf-8") as f:
        for line in f:
            if line.startswith(STOP_AT):
                break
            m = LINE_RE.match(line)
            if not m:
                continue
            quoted, named, hexbytes = m.groups()

            values = hexbytes.split()
            if len(values) != 1:          # multi-byte sequences have no single slot
                continue
            byte = int(values[0], 16)
            if byte in EXCLUDE_BYTES or byte in table:
                continue                  # first definition wins

            if quoted is not None:
                ch = quoted[-1] if quoted.startswith("\\") else quoted
                ascii_ = fold(ch)
            else:
                ascii_ = NAMED.get(named)

            if ascii_ is not None:
                table[byte] = ascii_
    return table


def main():
    table = parse()
    width = max((len(v) for v in table.values()), default=1) + 1

    out = sys.stdout
    out.write("// Generated by tools/gen_charmap_ascii.py -- do not edit by hand.\n")
    out.write("// Maps a GBA charmap byte to its ASCII spelling ('' = no equivalent).\n\n")
    out.write("#ifndef GUARD_DATA_CHARMAP_ASCII_H\n")
    out.write("#define GUARD_DATA_CHARMAP_ASCII_H\n\n")
    out.write(f"#define CHARMAP_ASCII_MAX {width}\n\n")
    out.write(f"static const char sCharmapToAscii[256][{width}] =\n{{\n")
    for byte in range(256):
        val = table.get(byte)
        if val is None:
            continue
        esc = val.replace("\\", "\\\\").replace('"', '\\"')
        out.write(f'    [0x{byte:02X}] = "{esc}",\n')
    out.write("};\n\n")
    out.write("#endif // GUARD_DATA_CHARMAP_ASCII_H\n")

    print(f"{len(table)} mappings, entry width {width}", file=sys.stderr)


if __name__ == "__main__":
    main()
