#!/usr/bin/env python3
"""Generate Showdown-style species names for forms that share a display name.

speciesName is capped at POKEMON_NAME_LENGTH, so every Urshifu form is spelled
"Urshifu" and every Rotom form "Rotom". Exporting those verbatim loses the form:
Showdown reads a bare "Urshifu" as Single Strike, which is Dark rather than
Water. Around 550 of the ~1350 species entries share a name this way.

The species enum already carries the information needed to disambiguate. Forms
are separate constants (SPECIES_URSHIFU_RAPID_STRIKE) and base forms are aliased
onto their canonical entry (SPECIES_URSHIFU = SPECIES_URSHIFU_SINGLE_STRIKE), so
taking the shortest constant for each species id and spelling it out yields
exactly what Showdown expects:

    SPECIES_URSHIFU_RAPID_STRIKE -> Urshifu-Rapid-Strike
    SPECIES_URSHIFU              -> Urshifu
    SPECIES_ROTOM_WASH           -> Rotom-Wash
    SPECIES_RAICHU_ALOLA         -> Raichu-Alola

The same spelling round-trips through trainerproc, which turns the written name
straight back into a constant, so a pasted export lands on the right form in
src/data/trainers.party too.

Only ambiguous species get an entry. Everything else keeps its display name,
which is nicer where it is already unique ("Farfetch'd" rather than
"Farfetchd", "Flabebe" with its accent folded).

Usage (from the repo root):
    python3 tools/gen_species_showdown_names.py > src/data/species_showdown_names.h
"""
import glob
import re
import sys
from collections import defaultdict

SPECIES_H = "include/constants/species.h"
SPECIES_INFO_GLOB = "src/data/pokemon/species_info/*.h"

ENUM_RE = re.compile(r"^\s+SPECIES_([A-Z0-9_]+)\s*=\s*(.+?),\s*$", re.M)
ENTRY_RE = re.compile(r"\[SPECIES_([A-Z0-9_]+)\]\s*=")
NAME_RE = re.compile(r'\.speciesName\s*=\s*_\("([^"]*)"\)')


def parse_enum():
    """constant name -> numeric species id, following aliases."""
    text = open(SPECIES_H, encoding="utf-8").read()
    literal, alias = {}, {}

    for name, rhs in ENUM_RE.findall(text):
        rhs = rhs.strip()
        if re.fullmatch(r"\d+", rhs):
            literal[name] = int(rhs)
        elif rhs.startswith("SPECIES_") and re.fullmatch(r"SPECIES_[A-Z0-9_]+", rhs):
            alias[name] = rhs[len("SPECIES_"):]

    # Aliases can chain, so resolve until nothing new appears.
    for _ in range(8):
        progressed = False
        for name, target in alias.items():
            if name not in literal and target in literal:
                literal[name] = literal[target]
                progressed = True
        if not progressed:
            break
    return literal


def parse_display_names():
    """constant name -> speciesName as written in the species_info tables."""
    names = {}
    for path in sorted(glob.glob(SPECIES_INFO_GLOB)):
        text = open(path, encoding="utf-8").read()
        marks = list(ENTRY_RE.finditer(text))
        for i, mark in enumerate(marks):
            end = marks[i + 1].start() if i + 1 < len(marks) else len(text)
            found = NAME_RE.search(text, mark.end(), end)
            if found:
                names[mark.group(1)] = found.group(1)
    return names


def showdown_name(constant):
    """SPECIES_URSHIFU_RAPID_STRIKE -> Urshifu-Rapid-Strike"""
    return "-".join(word.capitalize() for word in constant.split("_"))


def main():
    ids = parse_enum()
    display = parse_display_names()

    # Group every constant by the species it names, aliases included. Only the
    # canonical constant has a species_info entry, but the aliases are exactly
    # what makes the base form recoverable: SPECIES_URSHIFU is shorter than
    # SPECIES_URSHIFU_SINGLE_STRIKE and is the name Showdown wants.
    constants_by_id = defaultdict(list)
    for constant, species_id in ids.items():
        constants_by_id[species_id].append(constant)

    # Keep only species that actually exist in the data tables.
    display_by_id = {}
    for species_id, constants in constants_by_id.items():
        for constant in constants:
            if constant in display:
                display_by_id[species_id] = display[constant]
                break

    # A display name is ambiguous when more than one distinct species uses it.
    ids_by_display = defaultdict(set)
    for species_id, name in display_by_id.items():
        ids_by_display[name].add(species_id)

    overrides = []
    for species_id in sorted(display_by_id):
        canonical = min(constants_by_id[species_id], key=lambda c: (len(c), c))
        if len(ids_by_display[display_by_id[species_id]]) > 1:
            overrides.append((canonical, showdown_name(canonical)))

    out = sys.stdout
    out.write("// Generated by tools/gen_species_showdown_names.py -- do not edit by hand.\n")
    out.write("//\n")
    out.write("// Showdown-style names for species whose speciesName is shared with another\n")
    out.write("// form. Species not listed here are unambiguous and keep their display name.\n\n")
    out.write("#ifndef GUARD_DATA_SPECIES_SHOWDOWN_NAMES_H\n")
    out.write("#define GUARD_DATA_SPECIES_SHOWDOWN_NAMES_H\n\n")
    out.write("static const u8 *const sSpeciesShowdownNames[] =\n{\n")
    for constant, name in overrides:
        out.write(f'    [SPECIES_{constant}] = COMPOUND_STRING("{name}"),\n')
    out.write("};\n\n")
    out.write("#endif // GUARD_DATA_SPECIES_SHOWDOWN_NAMES_H\n")

    longest = max(overrides, key=lambda o: len(o[1]))
    print(f"{len(overrides)} ambiguous species of {len(constants_by_id)}; "
          f"longest name {len(longest[1])} chars ({longest[1]})", file=sys.stderr)


if __name__ == "__main__":
    main()
